### ISSUE TITLE
Font customization not working for more than one user accounts

### ISSUE THREAD

**Issue by bsidhipong** [iocave/customize-ui#33]
On a system-wide installation of vscode and customize-ui, I noticed that custom font override would only work for one of the accounts.  If I clean everything (~/.config/Code) for accounts A, and B, then whichever account I run Code first is the one where font customization works.  The other account simply has the original font.

Is there a place in the customize-ui code you can point me so I can have a look and try to narrow down the issue for you?  It may have something to do with permissions or SELinux labelling for files.

**Comment by knopp** [comment]
Unfortunately this is not going to work with multiple accounts out of box. CustomizeUI uses the monkey patch extension, which modifies the vscode extension to inject additional javascript files, which are located in your home directory. I assume that's the problem - other user account can't access them.

You can look at <vscode-installation>/app/out/boostrap-amd.js where it references the injected files. Maybe by modifying the permissions so that other users can read it this could work.

**Comment by bsidhipong** [comment]
Yup, that's what's happening.  The workaround is to make the account that ran the script first ugo+rx for the .config/Code -- that's not too bad of a workaround.
