### ISSUE TITLE
Error:  ENOENT: no such file or directory, open '\\.\c:\Users\HP\AppData\Roaming\Code\User\globalStorage\iocave.monkey-patch\modules\main.js'

### ISSUE THREAD

**Issue by maniac-en** [iocave/customize-ui#59]
I tried Customize UI but had some issues, so I planned to uninstall it, but since the installation, I get the following message error message, what's the fix for this?

```
 [Error: ENOENT: no such file or directory, open '\\.\c:\Users\HP\AppData\Roaming\Code\User\globalStorage\iocave.monkey-patch\modules\main.js'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: '\\\\.\\c:\\Users\\HP\\AppData\\Roaming\\Code\\User\\globalStorage\\iocave.monkey-patch\\modules\\main.js',
  phase: 'loading',
  moduleId: 'monkey/main',
  neededBy: [ '===anonymous3===' ]
```

**Comment by knopp** [comment]
This likely happened because you uninstalled CustomizeUI (and monkey-patch) without disabling monkey first ("Disable Monkey Patch" command). Monkeypatch modifies vscode installation to inject the javascript, and now it references files that don't exist.

Easiest  way would be to simply reinstall vscode, which will overwrite patched files.

**Comment by maniac-en** [comment]
I have lot of settings done in vscode, Is it possible to just delete the dedicated folder and fix the issue?

**Comment by knopp** [comment]
Reinstalling vscode will not modify any of your settings. Those are not part of vscode installation (which IIRC on windows residers in C:\Users\{UserName}\AppData\Local\Programs\Microsoft VS Code).

**Comment by maniac-en** [comment]
Reinstalling resolved my issue. Thanks for your help, I'm closing the issue now.
